# Generated by Django 3.2.7 on 2021-09-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Time_of_registration', models.DateTimeField(auto_now_add=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('Route_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('fare', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('Time_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Arrival_Time', models.TimeField()),
                ('Departure_Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('Train_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Train_name', models.CharField(max_length=30)),
                ('Route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookticket.routes')),
                ('Time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookticket.time')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('Ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Compartment_no', models.CharField(max_length=5)),
                ('Berth_type', models.CharField(max_length=10)),
                ('Seat_No', models.IntegerField()),
                ('Train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookticket.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookticket.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('Age', models.IntegerField()),
                ('Dare_of_booking', models.DateTimeField(auto_now_add=True)),
                ('On_boarding_Date', models.DateField()),
                ('Aadhar', models.CharField(max_length=12)),
                ('Phone', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookticket.customer')),
                ('Ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookticket.tickets')),
            ],
        ),
    ]
